#!/usr/bin/env bash
#: Title          :
#: Date           :
#: Author         : Rafael Baez
#: Version        : 1.0
#: Description    :
#: Options        :
# ------------------------------------------------------------------------------
extract() {
	if [[ -f "$1" ]]; then
		case "$1" in
		*.tar.bz2) tar xjf $1 && cd "$(basename "$1" .tar.bz2)" ;;
		*.tar.gz) tar xzf $1 && cd "$(basename "$1" .tar.gz)" ;;
		*.tar.xz) tar xf $1 && cd "$(basename "$1" .tar.xz)" ;;
		*.bz2) bunzip2 $1 && cd "$(basename "$1" .bz2)" ;;
		*.rar) unrar e $1 && cd "$(basename "$1" .rar)" ;;
		*.gz) gunzip $1 && cd "$(basename "$1" .gz)" ;;
		*.tar) tar xf $1 && cd "$(basename "$1" .tar)" ;;
		*.tbz2) tar xjf $1 && cd "$(basename "$1" .tbz2)" ;;
		*.tgz) tar xzf $1 && cd "$(basename "$1" .tgz)" ;;
		*.zip) 7z x $1 && cd "$(basename "$1" .zip)" ;;
		*.Z) uncompress $1 && cd "$(basename "$1" .Z)" ;;
		*.7z) 7z x $1 && cd "$(basename "$1" .7z)" ;;
		*) echo ""$1" cannot be extracted via extract()" ;;
		esac
	else
		echo ""$1" is not a valid file."
	fi
}

gnu-build() {
	./configure --prefix=/usr/local
	if [[ "$?" == 0 ]]; then make -j23; fi
	if [[ "$?" == 0 ]]; then sudo make install; fi
}

check_install() {
	dpkg-query -W --showformat='${Status}\n' $@ | grep "install ok installed" &>/dev/null
	echo $?
}
