#!/usr/bin/env bash
#: Title          :
#: Date           :
#: Author         : Rafael Baez
#: Version        : 2.0
#: Description    :
#: Options        :
# ------------------------------------------------------------------------------
function help() {
  echo "Usage: $(basename "$0") [OPTIONS] [arg ...]"
  echo "--help                  Display help"
  echo "--version               Display version of script"
  echo "--print                 Print arguments"
}
function version() {
  echo "Version 3.1"
}
function print() {
  echo "Arguments are: $*"
}
# ------------------------------------------------------------------------------
# Variables
# ------------------------------------------------------------------------------
NDATE=$(date +%m.%d.%y)
NMONTH=$(date +%B)
NTIME=$(date +%X)
NYEAR=$(date +%Y)
JJRNL=$(cat $HOME/jjrnl.conf)
# ------------------------------------------------------------------------------
# Start putting your functions for the script under here.
# ------------------------------------------------------------------------------
if [[ ! -f $HOME/jjrnl.conf ]]; then
  echo -e "Would you like to create a configuration file?"
  read ANSR
  case $ANSR in
  -Y | -y | -YES | -yes)
    touch $HOME/jjrnl.conf
    read -p "Enter root directory of the journal's folder: " JRD
    echo $JRD >>$HOME/jjrnl.conf
    ;;
  -N | -n | -NO | -no | no | NO)
    echo "You must specify journal location."
    exit 1
    ;;
  *)
    echo "Invalid Option: "$(echo $ANSR)"" 1>&2
    echo "Try --help for more options." 1>&2
    exit 1
    ;;
  esac
fi

_entry() {
  if [[ ! -d ${DIR:-"$JJRNL/$NYEAR/$NMONTH"} ]]; then
    mkdir -p ${DIR:-"$JJRNL/$NYEAR/$NMONTH"}
    cd ${DIR:-"$JRNLL/$NYEAR/$NMONTH"}
    echo -e "--> <-- \n -->> $NTIME <<-- \n-->     <--" >>"$NDATE"
    nano -$ "$NDATE"
  else
    cd ${DIR:-"$JJRNL/$NYEAR/$NMONTH"}
    echo -e "--> <-- \n -->> $NTIME <<-- \n-->     <--" >>"$NDATE"
    nano -$ "$NDATE"
  fi
}

_update() {
  :
}

_topic() {
  read -p "Topic Name:  " TNAME
  : '* Write a func to check for a file made day of &&
     if file exits open that file.
'
  if [[ ! -d ${DIR:-"$JJRNL/$NYEAR/Topics"} ]]; then
    mkdir -p ${DIR:-"$JJRNL/$NYEAR/Topics"}
    cd ${DIR:-"$JRNLL/$NYEAR/Topics"}
    echo -e "--> $TNAME.$NDATE <<-- \n-->     <--" >>"$TNAME.$NDATE"
    nano -$ "$TNAME.$NDATE"
  else
    cd ${DIR:-"$JJRNL/$NYEAR/Topics"}
    echo -e "--> $TNAME.$NTIME <<-- \n-->     <--" >>"$TNAME.$NDATE"
    nano -$ "$TNAME.$NDATE"
  fi
}

_concept() {
  read -p "Concept Name:  " CCNAME
  : '* Write a func to check for a file made day of &&
       if file exits open that file.
  '
  if [[ ! -d ${DIR:-"$JJRNL/$NYEAR/Concepts"} ]]; then
    mkdir -p ${DIR:-"$JJRNL/$NYEAR/Concepts"}
    cd ${DIR:-"$JRNLL/$NYEAR/Concepts"}
    echo -e "--> $CCNAME.$NTIME <<-- \n-->     <--" >>"$CCNAME.$NDATE"
    nano -$ "$CCNAME.$NDATE"
  else
    cd ${DIR:-"$JJRNL/$NYEAR/Concepts"}
    echo -e "--> $CCNAME.$NTIME <<-- \n-->     <--" >>"$CCNAME.$NDATE"
    nano -$ "$CCNAME.$NDATE"
  fi
}
# ------------------------------------------------------------------------------
# Parsing command line arguments
if [[ "$#" -eq 0 ]]; then
  echo "No Paramater Supplied: Try Again!"
elif [[ "$#" != "" ]]; then
  case "$1" in
  -h | --help | help)
    help
    exit 1
    ;;
  -v | --version | version)
    version
    exit 1
    ;;
  -p | --print | print)
    print "$@"
    exit 1
    ;;
  -new | "$2" | --new | "$2")
    case "$2" in
    entry)
      _entry
      ;;
    update)
      _update
      ;;
    topic)
      _topic
      ;;
    concept)
      _concept
      ;;
    *)
      if [[ $2 == "" ]]; then
        echo "No Paramater Supplied: Try Again!"
      else
        echo "Invalid Option: "$2"" 1>&2
        echo "Try --help for more options." 1>&2
      fi
      exit 1
      ;;
    esac
    ;;
  *)
    echo -e "Invalid Option: "$@"" 1>&2
    echo "Try --help for more options." 1>&2
    exit 1
    ;;
  esac
fi
