#!/bin/bash
#########################################################
#							#
# This are NScripts v3.6				#
#							#
# Licensed under the GNU GENERAL PUBLIC LICENSE 3	#
#							#
# Copyright 2007 - 2009 Christopher Bratusek		#
#							#
#########################################################

wdir=$(echo $NEMO_SCRIPT_SELECTED_URIS | sed -e 's/file:\/\///g' -e 's/\%20/\\ /g')

if [[ $(which gksu) != "" ]]; then
	gksu -u root "gnome-terminal --working-directory=\"$wdir\""
else 	zenity --info --text="gksu is not installed or not in $PATH" --title="Error"
fi
