#!/bin/bash
terminator=$(which terminator)
terminator -e 'mplayer -nolirc -noar -vf eq -vf screenshot -vfm ffmpeg -msgcolor -osdlevel 3 -volume 80 -volstep 5 -use-filename-title -shuffle -playlist <(find "$PWD" -type f -name "*.mp3")'
