#!/bin/bash
#gnome-terminal -e "~/.gnome2/nautilus-scripts/ISO/Dir 2 ISO"

echo -n "Enter name of ISO image to be created (eg cdName.iso): "
read -e isoName

echo -n "What is(are) the directory path(s) you want to archive into an ISO? (eg Dir1, Dir2...): "
read -e dirName

#mkisofs -o $isoName $dirName
xorrisofs -R -J -o $isoName $dirName
echo "Image saved in file://$isoName"

echo -n "Do you wish to delete the source folder/directory? y/n"
read -e delsrc

if ($delsrc == "y")
{
	rm -R $delsrc;
	echo "Source folder $delsrc has been deleted";
}
fi

