#!/bin/bash
#script via TheeMahn
for I in `echo $*`
do
  foo=`gksudo -u root -k -m "enter your password for root terminal
access" /bin/echo "got r00t?"`
#sudo mkdir /media/ISO
sudo umount /media/ISO
sudo mount -o loop -t iso9660 $I /media/ISO
done
