#!/bin/bash
#########################################################
#							#
# This are NScripts v3.6				#
#							#
# Licensed under the GNU GENERAL PUBLIC LICENSE 3	#
#							#
# Copyright 2007 - 2009 Christopher Bratusek		#
#							#
#########################################################

echo $NEMO_SCRIPT_SELECTED_URIS > ~/.gnome2/temp_shred_list

zenity --question --title "Shredder" --text "Really want to shred the selected file(s)?\nShredding means  to *absolutely* delete them!\n\nThe file is beeing overwritten 50 times and is then very difficult to recover!\n \nThe following files are marked to be shred:\n $(cat ~/.gnome2/temp_shred_list | sed -e 's/\%20/\ /g' -e 's/.*\///g')"

if (( $? == 0 )); then
	for file in $(cat ~/.gnome2/temp_shred_list); do

		shortfile=$(echo $file | sed -e 's/\%20/\ /g' -e 's/.*\///g')
		file_name=$(echo $file | sed -e 's/file:\/\///g' -e 's/\%20/\ /g')

		shred -u -z -n 50 --random-source=/dev/urandom "$file_name"
		if (( $? == 0 )); then
			zenity --info --text="$shortfile has been shred" --title "Success"
		else	zenity --info --text="$shortfile couldn't be shred" --title "Failure"
		fi
	done
fi

rm -f ~/.gnome2/temp_shred_list
unset XRETURN
